channels:
  - conda-forge
  - bioconda
#  - ccb-sb # for r-ggrastr
#  - jonaszierer # available on conda for linux only
  - defaults
dependencies:
  - python =3.6
  - r-base =3.6.2
  - bioconda::snakemake-minimal =5.17.0
  - jinja2 =2.10
  - networkx =2.1
  - matplotlib =3.2.1
  - graphviz =2.42.3
  - bcftools =1.9
  - samtools =1.9
  - htslib =1.9
  - bwa =0.7.17
  - pysam =0.15.0
  - htslib =1.9
  - FastQC =0.11.6
  - multiqc =1.7 
  - fastq-screen =0.14.0
  - bowtie2 =2.3.5
  - seqtk =1.3
  - bedtools =2.29.0
  - jonaszierer::pcangsd =0.98.2
  - r-tidyverse =1.3.0
  - r-ggpubr =0.3.0
  - r-gridextra =2.3
  - r-reshape2 =1.4.4
  - r-scales =1.1.1
  - r-corrplot =0.84
  - r-poibin =1.5
  - r-viridis =0.5.1
  - r-ggupset =0.3.0
  - ccb-sb::r-ggrastr =0.1.7
  - r-bedr =1.0.7
  - r-boot =1.3_25
  - r-rcolorbrewer =1.1_2
  - r-zoo =1.8_8
  - r-rgbif =2.2.0
  - r-quantreg =5.55
  - r-data.table =1.12.8
  - r-reader =1.0.6

  # external dependencies:
  # ancestry_hmm # version 0.94 is called by ancestry_hmm
  # angsd =0.932 # comes with htslib 1.10.2 and is linked to that library
  # picard =2.7.1 path to picard-tools-2.7.1/ loaded as $PICARD
  # and JAVA 1.8 to run picard MarkDuplicates
